from ocelot import *

#autogenerated on 2016/05/18 17:10:48
sh3e = Sextupole(l=0.0436278651,k2=0)
gs = Marker()
sf2a = Sextupole(l=0.0872557302,k2=519.8705881)
sf2e = Sextupole(l=0.0872557302,k2=519.8705881)
ge = Marker()
sd1d_vcor = Hcor()
sf2a_vcor = Hcor()
tpwmarker = Marker()
sh1a_skwq = Marker()
bpm_10 = Monitor()
dl1e_1 = SBend(l=0.3120265159,angle=0.001377777778,k1=0,e1=0.0158561926,e2=-0.0127561926)
sh1a_vcor = Hcor()
dl1e_3 = SBend(l=0.3120265647,angle=0.002377777778,k1=0,e1=0.0085561926,e2=-0.0032061926)
dl1e_2 = SBend(l=0.3120265365,angle=0.001866666667,k1=0,e1=0.0127561926,e2=-0.0085561926)
dl1e_5 = SBend(l=0.3120268618,angle=0.005338837867,k1=0,e1=-0.0038438074,e2=0.0158561926)
sh2b_hcor = Hcor()
sh3e_skwq = Marker()
sh3e_vcor = Hcor()
qf6d = Quadrupole(l=0.3385522332,k1=5.581549062)
qf6b = Quadrupole(l=0.3385522332,k1=5.581549062)
bpm_04 = Monitor()
bpm_05 = Monitor()
bpm_06 = Monitor()
bpm_07 = Monitor()
bpm_01 = Monitor()
bpm_02 = Monitor()
bpm_03 = Monitor()
sf2e_vcor = Hcor()
bpm_08 = Monitor()
bpm_09 = Monitor()
sd1e_vcor = Hcor()
sf2a_hcor = Hcor()
sh1a = Sextupole(l=0.0436278651,k2=0)
qf4e = Quadrupole(l=0.184982148,k1=3.403908672, eid="qf4e")
qf4d = Quadrupole(l=0.184982148,k1=3.403908672, eid="qf4d")
qd3e = Quadrupole(l=0.1413542829,k1=-3.954514823)
qf4a = Quadrupole(l=0.184982148,k1=3.403908672)
qd3a = Quadrupole(l=0.1413542829,k1=-3.954514823)
sh3e_hcor = Hcor()
sh2b = Sextupole(l=0.0436278651,k2=0)
#sf2e_skwq = multipole(ksl={ 0})
sf2e_skwq = Marker()
dq1d = SBend(l=0.8970207743,angle=0.01297777778,k1=-2.214925439,e1=0.0146,e2=0.0146)
dq1b = SBend(l=0.8970207743,angle=0.01297777778,k1=-2.214925439,e1=0.0146,e2=0.0146)
of1b0 = Octupole(l=0,k3=0)
sd1d = Sextupole(l=0.07242225607,k2=-545.07608)
sd1e = Sextupole(l=0.07242225607,k2=-560.8672496)
sd1b = Sextupole(l=0.07242225607,k2=-545.07608)
p4cell = Marker()
sd1a = Sextupole(l=0.07242225607,k2=-560.8672496)
sd1b_hcor = Hcor()
sh1a_hcor = Hcor()
sf2e_hcor = Hcor()
sd1d_hcor = Hcor()
dq2c_2 = SBend(l=0.3490238169,angle=0.003488888889,k1=-2.046809351,e1=0,e2=0.00785)
dq2c_1 = SBend(l=0.3490238169,angle=0.003488888889,k1=-2.046809351,e1=0.00785,e2=0)
sd1e_hcor = Hcor()
sd1b_vcor = Hcor()
#sd1b_skwq = multipole(ksl={ 0})
sd1b_skwq = Marker()
sd1a_hcor = Hcor()
dl2d_5 = SBend(l=0.3120267335,angle=0.004316615644,k1=0,e1=0.0147061926,e2=-0.0049938074)
dl2d_4 = SBend(l=0.3120266188,angle=0.003133333333,k1=0,e1=0.0049938074,e2=0.0020561926)
dl2d_1 = SBend(l=0.3120265159,angle=0.001377777778,k1=0,e1=-0.0116061926,e2=0.0147061926)
dispbumpcenter = Marker()
dl2d_3 = SBend(l=0.3120265647,angle=0.002377777778,k1=0,e1=-0.0020561926,e2=0.0074061926)
dl2d_2 = SBend(l=0.3120265365,angle=0.001866666667,k1=0,e1=-0.0074061926,e2=0.0116061926)
#sd1e_skwq = multipole(ksl={ 0})
sd1e_skwq = Marker()
dl2b_5 = SBend(l=0.3120267335,angle=0.004316615644,k1=0,e1=-0.0049938074,e2=0.0147061926)
dl2b_4 = SBend(l=0.3120266188,angle=0.003133333333,k1=0,e1=0.0020561926,e2=0.0049938074)
dl2b_3 = SBend(l=0.3120265647,angle=0.002377777778,k1=0,e1=0.0074061926,e2=-0.0020561926)
dl2b_2 = SBend(l=0.3120265365,angle=0.001866666667,k1=0,e1=0.0116061926,e2=-0.0074061926)
dl2b_1 = SBend(l=0.3120265159,angle=0.001377777778,k1=0,e1=0.0147061926,e2=-0.0116061926)
#sh2b_skwq = multipole(ksl={ 0})
sh2b_skwq = Marker()
qd5d = Quadrupole(l=0.184982148,k1=-3.504739875)
qd5b = Quadrupole(l=0.184982148,k1=-3.504739875)
sh2b_vcor = Hcor()
qd2a = Quadrupole(l=0.184982148,k1=-4.073718868, eid="qd2a")
qd2e = Quadrupole(l=0.184982148,k1=-4.073718868)
#sf2a_skwq = multipole(ksl={ 0})
sf2a_skwq = Marker()
of1d0 = Octupole(l=0,k3=0)
qf1e = Quadrupole(l=0.2574044041,k1=4.618871045)
idmarker = Marker()
qf1a = Quadrupole(l=0.2574044041,k1=4.618871045, eid="qf1a")
cellcenter = Marker()
dl1e_4 = SBend(l=0.3120266188,angle=0.003133333333,k1=0,e1=0.0032061926,e2=0.0038438074)
#sd1a_skwq = multipole(ksl={ 0})
sd1a_skwq = Marker()
qf8b = Quadrupole(l=0.4223177342,k1=5.195887845)
qf8d = Quadrupole(l=0.4223177342,k1=5.195887845)
dl1a_5 = SBend(l=0.3120268618,angle=0.005338837867,k1=0,e1=0.0158561926,e2=-0.0038438074)
dl1a_4 = SBend(l=0.3120266188,angle=0.003133333333,k1=0,e1=0.0038438074,e2=0.0032061926)
qf4b = Quadrupole(l=0.184982148,k1=3.403908672)
dl1a_1 = SBend(l=0.3120265159,angle=0.001377777778,k1=0,e1=-0.0127561926,e2=0.0158561926)
dl1a_3 = SBend(l=0.3120265647,angle=0.002377777778,k1=0,e1=-0.0032061926,e2=0.0085561926)
dl1a_2 = SBend(l=0.3120265365,angle=0.001866666667,k1=0,e1=-0.0085561926,e2=0.0127561926)
sd1a_vcor = Hcor()
#sd1d_skwq = multipole(ksl={ 0})
sd1d_skwq = Marker()


# automatic drifts

ducell01 = Drift(l=2.313142711)
ducell02 = Drift(l=0.044500422)
ducell03 = Drift(l=0.0959813034)
ducell04 = Drift(l=0.20068817945)
ducell05 = Drift(l=0.0410101931)
ducell06 = Drift(l=0.0406542896)
ducell07 = Drift(l=0.065441798515)
ducell08 = Drift(l=0.475415842965)
ducell09 = Drift(l=0.048863209)
ducell10 = Drift(l=0.065441797)
ducell11 = Drift(l=0.0654417969)
ducell12 = Drift(l=0.091618518)
ducell13 = Drift(l=0.039265079)
ducell14 = Drift(l=0.048863209)
ducell15 = Drift(l=0.344532244)
ducell16 = Drift(l=0.065441797965)
ducell17 = Drift(l=0.04101019305)
ducell18 = Drift(l=0.08166437625)
ducell19 = Drift(l=0.0488632094)
ducell20 = Drift(l=0.07853015625)
ducell21 = Drift(l=0.07817409775)
ducell22 = Drift(l=0.1448445129)
ducell23 = Drift(l=0.03228461745)
ducell24 = Drift(l=0.04886321)
ducell25 = Drift(l=0.04886320155)
ducell26 = Drift(l=0.2643848629)
ducell27 = Drift(l=0.07817410575)
ducell28 = Drift(l=0.07853015625)
ducell29 = Drift(l=0.0488632034)
ducell30 = Drift(l=0.08166438325)
ducell31 = Drift(l=0.04101019805)
ducell32 = Drift(l=0.065441797965)
ducell33 = Drift(l=0.34453225)
ducell34 = Drift(l=0.0488632)
ducell35 = Drift(l=0.03926508)
ducell36 = Drift(l=0.091618516)
ducell37 = Drift(l=0.065441806)
ducell38 = Drift(l=0.0654418009)
ducell39 = Drift(l=0.048863206)
ducell40 = Drift(l=0.475415841965)
ducell41 = Drift(l=0.065441790515)
ducell42 = Drift(l=0.0406542906)
ducell43 = Drift(l=0.0410101951)
ducell44 = Drift(l=0.20068818345)
ducell45 = Drift(l=0.0959813054)
ducell46 = Drift(l=0.04450042)
ducell47 = Drift(l=2.31314272)

l_cant = 0.2
theta_cant = 2.e-3
cant = SBend(l = l_cant/2.0, angle=theta_cant / 2.)
#d0 = Drift(l=2.31314272 - l_cant/2.0)

lw = 0.023
nw = int ( (2.31314272 - l_cant/2.0) / lw )


d0 = Undulator(lperiod=lw, nperiods=nw, Kx=2.0)


undcell=(cant,d0,bpm_01,\
ducell02,gs,\
qf1a,\
ducell03,sh1a,\
sh1a_hcor,\
sh1a_vcor,\
sh1a_skwq,\
sh1a,\
ducell04,qd2a,\
ducell05,dl1a_5,\
dl1a_4,\
dl1a_3,\
dl1a_2,\
dl1a_1,\
ducell06,qd3a,\
ducell07,sd1a,\
sd1a_hcor,\
sd1a_vcor,\
sd1a_skwq,\
sd1a,\
ducell08,bpm_02,\
ducell09,qf4a,\
ducell10,dispbumpcenter,\
sf2a,\
sf2a_hcor,\
sf2a_vcor,\
sf2a_skwq,\
sf2a,\
ducell11,qf4b,\
ducell12,of1b0,\
ducell13,ge,\
ducell14,bpm_03,\
ducell15,gs,\
sd1b,\
sd1b_hcor,\
sd1b_vcor,\
sd1b_skwq,\
sd1b,\
ducell16,qd5b,\
ducell17,dl2b_1,\
dl2b_2,\
dl2b_3,\
dl2b_4,\
dl2b_5,\
ducell18,bpm_04,\
ducell19,qf6b,\
ducell20,dq1b,\
ducell21,qf8b,\
ducell22,ge,\
sh2b,\
sh2b_hcor,\
sh2b_vcor,\
sh2b_skwq,\
sh2b,\
ducell23,bpm_05,\
ducell24,gs,\
dq2c_1,\
cellcenter,\
dq2c_2,\
ducell25,bpm_06,\
tpwmarker,\
ducell26,qf8d,\
ducell27,dq1d,\
ducell28,qf6d,\
ducell29,bpm_07,\
ducell30,dl2d_5,\
dl2d_4,\
dl2d_3,\
dl2d_2,\
dl2d_1,\
ducell31,qd5d,\
ducell32,sd1d,\
sd1d_hcor,\
sd1d_vcor,\
sd1d_skwq,\
sd1d,\
ge,\
ducell33,bpm_08,\
ducell34,gs,\
ducell35,of1d0,\
ducell36,qf4b,\
ducell37,dispbumpcenter,\
sf2e,\
sf2e_hcor,\
sf2e_vcor,\
sf2e_skwq,\
sf2e,\
ducell38,qf4a,\
ducell39,bpm_09,\
ducell40,sd1e,\
sd1e_hcor,\
sd1e_vcor,\
sd1e_skwq,\
sd1e,\
ducell41,qd3a,\
ducell42,dl1e_1,\
dl1e_2,\
dl1e_3,\
dl1e_4,\
dl1e_5,\
ducell43,qd2a,\
ducell44,sh3e,\
sh3e_hcor,\
sh3e_vcor,\
sh3e_skwq,\
sh3e,\
ducell45,qf1a,\
ge,\
ducell46,bpm_10,\
d0,cant,idmarker)
