#autogenerated on 2016/05/18 17:10:48
from ocelot import *
from ocelot.gui.accelerator import *
from pylab import *

from h7ba import *
cant.angle = 0.0
lat = MagneticLattice( undcell )

#from t6ba import *

from scipy.integrate import simps

beam = Beam()
beam.E = 6.0


tws=twiss(lat, Twiss(), nPoints=100)
plot_opt_func(lat, tws, legend = False)
print tws[-1].Dx
plt.show()

constr = {cant:{'beta_x':3.20}, 'periodic':True}
#constr = {'end':{'Dx':0.0, 'Dxp':0.0}, 'start':{'beta_x':15.0, 'beta_y':30.0}}
#constr = {'end':{'Dx':0.0, 'Dxp':0.0}}

vars = [qf1a,qd2a,qd3a,qf4a]
match(lat, constr, vars, tws[0], max_iter=10000, min_i5=False)



tws=twiss(lat, Twiss(), nPoints = 1000)
plot_opt_func(lat, tws, legend = False)
print tws[-1].Dx
print qf1a.k1, qd2a.k1, qd3a.k1, qf4a.k1
plt.show()

eb = EbeamParams(lat, beam, nsuperperiod=1)
print(eb.emittance * 1.e12)
print(eb)
